apiVersion: v1
kind: Pod
metadata:
  name: react-app
  lables:
    app: react-app
spec:
  containers:
    - name: react-app
      image: rajkumar524/react-app:tagVersion
      ports:
        - containerPort: 8080
